<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ExamTest" tests="129" skipped="0" failures="6" errors="0" timestamp="2023-08-03T14:57:48" hostname="LAPTOP-JEP357O7" time="0.084">
  <properties/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.01"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 1" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 2" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 2" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 2" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 3" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 3" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 3" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 3" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 3" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 4" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 4" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 4" classname="ExamTest" time="0.0"/>
  <testcase name="Latihan 4" classname="ExamTest" time="0.001"/>
  <testcase name="Latihan 5" classname="ExamTest" time="0.011">
    <failure message="org.opentest4j.AssertionFailedError: Pemanggilan fungsi sum() seharusnya terdapat jeda waktu minimal 3 detik" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Pemanggilan fungsi sum() seharusnya terdapat jeda waktu minimal 3 detik
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at app//ExtentionsTestKt.returnTrue(ExtentionsTest.kt:11)
	at app//ExamTest$1$1$5$1$1.invokeSuspend(ExamTest.kt:193)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//ExamTest$1$1$5$1.invoke(ExamTest.kt:188)
	at app//ExamTest$1$1$5$1.invoke(ExamTest.kt:187)
	at app//org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at app//org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <testcase name="Latihan 5" classname="ExamTest" time="0.003">
    <failure message="org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 5 dan b adalah 5, fungsi sum() seharusnya mengembalikkan nilai 10" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 5 dan b adalah 5, fungsi sum() seharusnya mengembalikkan nilai 10
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at app//ExtentionsTestKt.returnTrue(ExtentionsTest.kt:11)
	at app//ExamTest$1$1$5$2$1.invokeSuspend(ExamTest.kt:200)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//ExamTest$1$1$5$2.invoke(ExamTest.kt:198)
	at app//ExamTest$1$1$5$2.invoke(ExamTest.kt:197)
	at app//org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at app//org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <testcase name="Latihan 5" classname="ExamTest" time="0.002">
    <failure message="org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 100 dan b adalah 7, fungsi sum() seharusnya mengembalikkan nilai 107" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 100 dan b adalah 7, fungsi sum() seharusnya mengembalikkan nilai 107
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at app//ExtentionsTestKt.returnTrue(ExtentionsTest.kt:11)
	at app//ExamTest$1$1$5$3$1.invokeSuspend(ExamTest.kt:207)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//ExamTest$1$1$5$3.invoke(ExamTest.kt:205)
	at app//ExamTest$1$1$5$3.invoke(ExamTest.kt:204)
	at app//org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at app//org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <testcase name="Latihan 5" classname="ExamTest" time="0.001">
    <failure message="org.opentest4j.AssertionFailedError: Pemanggilan fungsi multiple() seharusnya terdapat jeda waktu minimal 2 detik" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Pemanggilan fungsi multiple() seharusnya terdapat jeda waktu minimal 2 detik
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at app//ExtentionsTestKt.returnTrue(ExtentionsTest.kt:11)
	at app//ExamTest$1$1$5$4$1.invokeSuspend(ExamTest.kt:217)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//ExamTest$1$1$5$4.invoke(ExamTest.kt:212)
	at app//ExamTest$1$1$5$4.invoke(ExamTest.kt:211)
	at app//org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at app//org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <testcase name="Latihan 5" classname="ExamTest" time="0.002">
    <failure message="org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 6 dan b adalah 6, fungsi multiple() seharusnya mengembalikkan nilai 36" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 6 dan b adalah 6, fungsi multiple() seharusnya mengembalikkan nilai 36
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at app//ExtentionsTestKt.returnTrue(ExtentionsTest.kt:11)
	at app//ExamTest$1$1$5$5$1.invokeSuspend(ExamTest.kt:224)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//ExamTest$1$1$5$5.invoke(ExamTest.kt:222)
	at app//ExamTest$1$1$5$5.invoke(ExamTest.kt:221)
	at app//org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at app//org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <testcase name="Latihan 5" classname="ExamTest" time="0.002">
    <failure message="org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 5 dan b adalah 5, fungsi multiple() seharusnya mengembalikkan nilai 25" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Jika argumen untuk parameter a adalah 5 dan b adalah 5, fungsi multiple() seharusnya mengembalikkan nilai 25
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at app//ExtentionsTestKt.returnTrue(ExtentionsTest.kt:11)
	at app//ExamTest$1$1$5$6$1.invokeSuspend(ExamTest.kt:231)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//ExamTest$1$1$5$6.invoke(ExamTest.kt:229)
	at app//ExamTest$1$1$5$6.invoke(ExamTest.kt:228)
	at app//org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(scopes.kt:136)
	at app//org.spekframework.spek2.runtime.Executor$execute$result$2$exception$1$job$1.invokeSuspend(Executor.kt:84)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//org.spekframework.spek2.runtime.TaskRunner.runTask$lambda-2(executors.kt:26)
	at java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
